# Generated by Django 5.0.7 on 2024-08-18 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_necessidadedemanutencao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('intinerario', models.CharField(max_length=60)),
                ('sentido', models.CharField(max_length=30)),
                ('ponto_referencia', models.CharField(blank=True, max_length=60)),
                ('matricula_motorista', models.CharField(max_length=10)),
                ('matricula_cobrador', models.CharField(blank=True, max_length=10)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificacaoDeItens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incidentes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(null=True)),
                ('ocorrencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ocorrencia')),
            ],
        ),
    ]
