# Generated by Django 5.0.7 on 2024-08-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ocorrencia_incidentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacaoDeItens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(null=True)),
            ],
        ),
    ]
