from core.admin.telefone_emergencial_admin import TelefoneEmergencialAdmin
from core.admin.necessidades_de_manutencao_admin import NecessidadeDeManutencaoAdmin
from core.admin.incidentes_admin import IncidentesAdmin
from core.admin.ocorrencia_admin import OcorrenciaAdmin
from core.admin.verificacao_de_itens_admin import VerificacaoDeItensAdmin 
from core.admin.vistoria_admin import VistoriaAdmin, VistoriaIncidenteInline, VistoriaNecessidadeManutencaoInline, VistoriaVerificacaoItensInline

