from core.admin.telefone_emergencial_admin import TelefoneEmergencialAdmin
from core.admin.necessidades_de_manutencao_admin import NecessidadeDeManutencaoAdmin
from core.admin.verificacao_de_itens_admin import VerificacaoDeItensAdmin 